version: "3.9"

services:
  react-dev:
    image: node:20-alpine
    container_name: react-dev
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - REACT_APP_API_URL=http://localhost:5000/api
    command: sh -c "npm install && npm start"
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - backend-api
      - mysql-db

  backend-api:
    image: node:20-alpine
    container_name: backend-api
    working_dir: /app
    volumes:
      - ./i:/app
    ports:
      - "5000:5000"
    command: sh -c "npm install && npm start"
    restart: unless-stopped
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskflow_db
      MYSQL_USER: taskflow_user
      MYSQL_PASSWORD: taskflow_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      -
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin1
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      UPLOAD_LIMIT: 128M
      MEMORY_LIMIT: 256M
    depends_on:
      - mysql-db
    links:
      - mysql-db

volumes:
  node_modules:
  mysql_data: